version: 2
project_name: timeguard

builds:
  - id: timeguard
    main: .
    binary: timeguard
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/nirakar24/timeguard/cmd.Version={{ .Version }} -X github.com/nirakar24/timeguard/cmd.Commit={{ .Commit }} -X github.com/nirakar24/timeguard/cmd.Date={{ .Date }}

archives:
  - id: default
    builds:
      - timeguard
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

## Packaging targets (Homebrew & Scoop) removed per request.

nfpms:
  - id: linux-packages
    package_name: timeguard
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    homepage: https://github.com/nirakar24/timeguard
    description: "Advanced timezone & temporal edge-case toolkit"
    maintainer: "TimeGuard Maintainers <maintainers@example.com>"
    license: MIT
    formats:
      - deb
      - rpm

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
  groups:
    - title: Features
      regexp: '^(feat|feature)(\(|:)'
    - title: Fixes
      regexp: '^(fix)(\(|:)'
    - title: Refactoring
      regexp: '^(refactor)(\(|:)'
    - title: Misc
      regexp: '.*'

sboms:
  - id: archive-sbom
    artifacts: archive
    formats: [cyclonedx-json]

signs:
  - id: checksum-sign
    cmd: sh
    args: ["-c", "echo placeholder-signature > $signature"]
    artifacts: checksum

release:
  github:
    owner: nirakar24
    name: timeguard
  draft: false
  prerelease: auto
snapshot:
  name_template: "{{ .Version }}-SNAPSHOT-{{ .ShortCommit }}"
