name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
      - name: Vet
        run: go vet ./...
      - name: Tests
        run: go test -count=1 ./...
      - name: GoReleaser check (config sanity)
        run: |
          curl -sL https://github.com/goreleaser/goreleaser/releases/download/v2.2.0/goreleaser_Linux_x86_64.tar.gz \
          | tar xz goreleaser
          ./goreleaser check
      - name: Snapshot (no publish)
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: v2.2.0   # pin a v2.x version
          args: release --snapshot --skip=publish --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
