name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'

permissions:
  contents: write
  pull-requests: read

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Verify Go
        run: go version

      - name: Tidy check
        run: |
          go mod tidy
          git diff --exit-code || (echo 'Run go mod tidy locally and commit changes.' && exit 1)

      - name: Tests
        run: go test -count=1 ./...

      - name: GoReleaser Check
        run: |
          curl -sL https://github.com/goreleaser/goreleaser/releases/latest/download/goreleaser_Linux_x86_64.tar.gz | tar xz goreleaser
          ./goreleaser check

      - name: Release
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
