name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'

permissions:
  contents: write
  pull-requests: read

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
      - name: Tidy check
        run: |
          go mod tidy
          git diff --exit-code || (echo "Run 'go mod tidy' locally" && exit 1)
      - name: Tests
        run: go test -count=1 ./...
      - name: GoReleaser check
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: v2.2.0
          args: check
      - name: Install Syft (for SBOM generation)
        uses: anchore/sbom-action/download-syft@v0.17.5
      - name: Release
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: v2.2.0     # ensure v2 binary
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # If Homebrew tap push fails, replace above with:
          # GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
